actors = ['Tony Chiu-Wai Leung',
 'Cung Le',
 'Qingxiang Wang',
 'Elvis Tsui',
 'Song Hye-Kyo',
 'Kar-Yung Lau',
 'Chau Yee Tsang',
 'Hoi-Pang Lo',
 'Shun Lau',
 'Xiaofei Zhou',
 'Mancheng Wang',
 'Ting Yip Ng',
 'Man Keung Cho',
 'Tony Ling',
 'Tielong Shang',
 'Ziyi Zhang',
 'Kai-Shui Hung',
 'Darren Leung',
 'Meng Lo',
 'Huiwen Li',
 'Benshan Zhao',
 'Chang Chen',
 'Chunxiong Yin',
 'Shenyang Xiao',
 'Han Tong',
 'Haifeng Ni',
 'Shilin Xiao',
 'Gen Peng',
 'Yixuan Wu',
 'Woo-Ping Yuen',
 'Macy Chan',
 'Wenfei Chen',
 'Yan Chen',
 'Yijing Chen',
 'Julian Cheung',
 'Manyu Cui',
 'Jingbao Ding',
 'Minglai Fan',
 'Wenting He',
 'Xun He',
 'Jeana Ho',
 'Chiu-Lam Ko',
 'To-Hoi Kong',
 'Yingzhi Kong',
 'Yee Man Lee',
 'Jeanette Leung',
 'Chunfen Li',
 'Ruipeng Li',
 'Sisi Li',
 'Libing Lin',
 'Ke Liu',
 'Ping Liu',
 'Qi Man',
 'Meixin',
 'Qiong Ning',
 'Yuxin Pei',
 'Siu Ping-Lam',
 'Xinyu Ren',
 'Yongliang Sui',
 'Xiangling Wang',
 'Huanhuan Wei',
 'Jiarui Wei',
 'Ling Wu',
 'Yunfei Wu',
 'Xiaocui Yu',
 'Cheung-Yan Yuen',
 'Bingqian Zhang',
 'Jin Zhang',
 'Shuting Zhang',
 'Yalei Zhang',
 'Yuan Zhang Zhang',
 'Xintong Zhao',
 'Li Zheng',
 'Xiaoyun Zheng',
 'Qin Zhong',
 'Chengcheng Fang',
 'Charlie Yeung',
 'Tony Chiu-Wai Leung',
 'Gong Li',
 'Faye Wong',
 'Takuya Kimura',
 'Ziyi Zhang',
 'Carina Lau',
 'Chang Chen',
 'Dong Jie',
 'Maggie Cheung',
 'Thongchai McIntyre',
 'Wang Sum',
 'Siu Ping-Lam',
 'Farini Cheung',
 'Sien Cheung',
 'Wah Hong',
 'Xinyu Jiang',
 'To-Hoi Kong',
 'Alice Lee',
 'Siu Ming Lee',
 'Fei-lin Miao',
 'Ting Yip Ng',
 'Ching Siu-Lung',
 'Ben Yuen',
 'Gong Li',
 'Chang Chen',
 'Feng Tien',
 'Chun-Luk Chan',
 'Jianjun Zhou',
 'Wing Tong Sheung',
 'Kim Tak Wong',
 'Siu Man Ting',
 'Lai Fu Yim',
 'Cheng You Shin',
 'Wing-Kong Siu',
 'Kar Fai Lee',
 'Chi Keong Un',
 'Robert Downey Jr.',
 'Alan Arkin',
 'Ele Keats',
 'Christopher Buchholz',
 'Regina Nemni',
 'Luisa Ranieri',
 'Cecilia Luci',
 'Karima Machehour',
 'Riccardo Manfredi',
 'Valerio Burroni',
 'Pelino Tarantelli',
 'Maria Bosio',
 'Carla Milani',
 'Vinicio Milani',
 'Ugo Quattrini',
 'Jason Cardone',
 'Carin Berger',
 'Enrica Antonioni',
 'Maggie Cheung',
 'Tony Chiu-Wai Leung',
 'Siu Ping-Lam',
 "Tung Cho 'Joe' Cheung",
 'Rebecca Pan',
 'Kelly Lai Chen',
 'Man-Lei Chan',
 'Kam-Wah Koo',
 'Szu-Ying Chien',
 'Paulyn Sun',
 'Roy Cheung',
 'Po-chun Chow',
 'Hsien Yu',
 'Julien Carbon',
 'Laurent Courtiaud',
 'Charles de Gaulle',
 'Leslie Cheung',
 'Tony Chiu-Wai Leung',
 'Chang Chen',
 'Gregory Dayton',
 'Shirley Kwan',
 'Leon Lai',
 'Michelle Reis',
 'Takeshi Kaneshiro',
 'Charlie Yeung',
 'Karen Mok',
 'Fai-Hung Chan',
 'Man-Lei Chan',
 'Toru Saito',
 'To-Hoi Kong',
 'Lee-Na Kwan',
 'Yuhao Wu',
 'Brigitte Lin',
 'Leslie Cheung',
 'Maggie Cheung',
 'Tony Chiu-Wai Leung',
 'Jacky Cheung',
 'Tony Ka Fai Leung',
 'Li Bai',
 'Carina Lau',
 'Charlie Yeung',
 'Joey Wang',
 'Shun Lau',
 'Li Yin',
 'Brigitte Lin',
 'Tony Chiu-Wai Leung',
 'Faye Wong',
 'Takeshi Kaneshiro',
 'Valerie Chow',
 'Piggy Chan',
 'Lee-Na Kwan',
 'Zhiming Huang',
 'Liang Zhen',
 'Songshen Zuo',
 'Thom Baker',
 'Rico Chu',
 'Vickie Eng',
 'Lynne Langdon',
 'Leslie Cheung',
 'Maggie Cheung',
 'Andy Lau',
 'Carina Lau',
 'Rebecca Pan',
 'Jacky Cheung',
 'Tony Chiu-Wai Leung',
 'Danilo Antunes',
 'Mei-Mei Hung',
 'Ling-Ling Hung',
 'Tita Muñoz',
 'Alicia Alonzo',
 'Elena Lim So',
 'Maritoni Fernandez',
 'Angela Ponos',
 'Nonong Talbo',
 'Andy Lau',
 'Maggie Cheung',
 'Jacky Cheung',
 'Alex Man',
 'Ronald Wong',
 'To-Hoi Kong',
 'Ching Wai',
 'Kau Lam',
 'William Chang',
 'Ang Wong',
 'Pa-Ching Huang',
 'Chi-Fai Chan',
 'Man-Ho Chan',
 'Tseng Chang',
 'Wing-Cheung Cheung',
 'Wing-Hon Cheung',
 'Shan Chin',
 'Kam Kong Chow',
 'Kwai-Bo Chun',
 'Pak Fei',
 'Tat-Wah Gan',
 'Fan Hui',
 'Long Kong',
 'Chi Kit Lee',
 'Keung-Fai Pong',
 'Tai-Wo Tang',
 'Chi Wai Wong',
 'Kim Fung Wong']


dictionary = {'2046': ['Tony Chiu-Wai Leung',
          'Gong Li',
          'Faye Wong',
          'Takuya Kimura',
          'Ziyi Zhang',
          'Carina Lau',
          'Chang Chen',
          'Dong Jie',
          'Maggie Cheung',
          'Thongchai McIntyre',
          'Wang Sum',
          'Siu Ping-Lam',
          'Farini Cheung',
          'Sien Cheung',
          'Wah Hong',
          'Xinyu Jiang',
          'To-Hoi Kong',
          'Alice Lee',
          'Siu Ming Lee',
          'Fei-lin Miao',
          'Ting Yip Ng',
          'Ching Siu-Lung',
          'Ben Yuen'],
 'As Tears Go By': ['Andy Lau',
                    'Maggie Cheung',
                    'Jacky Cheung',
                    'Alex Man',
                    'Ronald Wong',
                    'To-Hoi Kong',
                    'Ching Wai',
                    'Kau Lam',
                    'William Chang',
                    'Ang Wong',
                    'Pa-Ching Huang',
                    'Chi-Fai Chan',
                    'Man-Ho Chan',
                    'Tseng Chang',
                    'Wing-Cheung Cheung',
                    'Wing-Hon Cheung',
                    'Shan Chin',
                    'Kam Kong Chow',
                    'Kwai-Bo Chun',
                    'Pak Fei',
                    'Tat-Wah Gan',
                    'Fan Hui',
                    'Long Kong',
                    'Chi Kit Lee',
                    'Keung-Fai Pong',
                    'Tai-Wo Tang',
                    'Chi Wai Wong',
                    'Kim Fung Wong'],
 'Ashes of Time': ['Brigitte Lin',
                   'Leslie Cheung',
                   'Maggie Cheung',
                   'Tony Chiu-Wai Leung',
                   'Jacky Cheung',
                   'Tony Ka Fai Leung',
                   'Li Bai',
                   'Carina Lau',
                   'Charlie Yeung',
                   'Joey Wang',
                   'Shun Lau',
                   'Li Yin'],
 'Chungking Express': ['Brigitte Lin',
                       'Tony Chiu-Wai Leung',
                       'Faye Wong',
                       'Takeshi Kaneshiro',
                       'Valerie Chow',
                       'Piggy Chan',
                       'Lee-Na Kwan',
                       'Zhiming Huang',
                       'Liang Zhen',
                       'Songshen Zuo',
                       'Thom Baker',
                       'Rico Chu',
                       'Vickie Eng',
                       'Lynne Langdon'],
 'Days of Being Wild': ['Leslie Cheung',
                        'Maggie Cheung',
                        'Andy Lau',
                        'Carina Lau',
                        'Rebecca Pan',
                        'Jacky Cheung',
                        'Tony Chiu-Wai Leung',
                        'Danilo Antunes',
                        'Mei-Mei Hung',
                        'Ling-Ling Hung',
                        'Tita Muñoz',
                        'Alicia Alonzo',
                        'Elena Lim So',
                        'Maritoni Fernandez',
                        'Angela Ponos',
                        'Nonong Talbo'],
 'Eros': ['Gong Li',
          'Chang Chen',
          'Feng Tien',
          'Chun-Luk Chan',
          'Jianjun Zhou',
          'Wing Tong Sheung',
          'Kim Tak Wong',
          'Siu Man Ting',
          'Lai Fu Yim',
          'Cheng You Shin',
          'Wing-Kong Siu',
          'Kar Fai Lee',
          'Chi Keong Un',
          'Robert Downey Jr.',
          'Alan Arkin',
          'Ele Keats',
          'Christopher Buchholz',
          'Regina Nemni',
          'Luisa Ranieri',
          'Cecilia Luci',
          'Karima Machehour',
          'Riccardo Manfredi',
          'Valerio Burroni',
          'Pelino Tarantelli',
          'Maria Bosio',
          'Carla Milani',
          'Vinicio Milani',
          'Ugo Quattrini',
          'Jason Cardone',
          'Carin Berger',
          'Enrica Antonioni'],
 'Fallen Angels': ['Leon Lai',
                   'Michelle Reis',
                   'Takeshi Kaneshiro',
                   'Charlie Yeung',
                   'Karen Mok',
                   'Fai-Hung Chan',
                   'Man-Lei Chan',
                   'Toru Saito',
                   'To-Hoi Kong',
                   'Lee-Na Kwan',
                   'Yuhao Wu'],
 'Happy Together': ['Leslie Cheung',
                    'Tony Chiu-Wai Leung',
                    'Chang Chen',
                    'Gregory Dayton',
                    'Shirley Kwan'],
 'In the Mood for Love': ['Maggie Cheung',
                          'Tony Chiu-Wai Leung',
                          'Siu Ping-Lam',
                          "Tung Cho 'Joe' Cheung",
                          'Rebecca Pan',
                          'Kelly Lai Chen',
                          'Man-Lei Chan',
                          'Kam-Wah Koo',
                          'Szu-Ying Chien',
                          'Paulyn Sun',
                          'Roy Cheung',
                          'Po-chun Chow',
                          'Hsien Yu',
                          'Julien Carbon',
                          'Laurent Courtiaud',
                          'Charles de Gaulle'],
 'The Grandmaster': ['Tony Chiu-Wai Leung',
                     'Cung Le',
                     'Qingxiang Wang',
                     'Elvis Tsui',
                     'Song Hye-Kyo',
                     'Kar-Yung Lau',
                     'Chau Yee Tsang',
                     'Hoi-Pang Lo',
                     'Shun Lau',
                     'Xiaofei Zhou',
                     'Mancheng Wang',
                     'Ting Yip Ng',
                     'Man Keung Cho',
                     'Tony Ling',
                     'Tielong Shang',
                     'Ziyi Zhang',
                     'Kai-Shui Hung',
                     'Darren Leung',
                     'Meng Lo',
                     'Huiwen Li',
                     'Benshan Zhao',
                     'Chang Chen',
                     'Chunxiong Yin',
                     'Shenyang Xiao',
                     'Han Tong',
                     'Haifeng Ni',
                     'Shilin Xiao',
                     'Gen Peng',
                     'Yixuan Wu',
                     'Woo-Ping Yuen',
                     'Macy Chan',
                     'Wenfei Chen',
                     'Yan Chen',
                     'Yijing Chen',
                     'Julian Cheung',
                     'Manyu Cui',
                     'Jingbao Ding',
                     'Minglai Fan',
                     'Wenting He',
                     'Xun He',
                     'Jeana Ho',
                     'Chiu-Lam Ko',
                     'To-Hoi Kong',
                     'Yingzhi Kong',
                     'Yee Man Lee',
                     'Jeanette Leung',
                     'Chunfen Li',
                     'Ruipeng Li',
                     'Sisi Li',
                     'Libing Lin',
                     'Ke Liu',
                     'Ping Liu',
                     'Qi Man',
                     'Meixin',
                     'Qiong Ning',
                     'Yuxin Pei',
                     'Siu Ping-Lam',
                     'Xinyu Ren',
                     'Yongliang Sui',
                     'Xiangling Wang',
                     'Huanhuan Wei',
                     'Jiarui Wei',
                     'Ling Wu',
                     'Yunfei Wu',
                     'Xiaocui Yu',
                     'Cheung-Yan Yuen',
                     'Bingqian Zhang',
                     'Jin Zhang',
                     'Shuting Zhang',
                     'Yalei Zhang',
                     'Yuan Zhang Zhang',
                     'Xintong Zhao',
                     'Li Zheng',
                     'Xiaoyun Zheng',
                     'Qin Zhong',
                     'Chengcheng Fang',
                     'Charlie Yeung']}

filmsList = ['2046', 'As Tears Go By', 'Ashes of Time', 'Chungking Express', 'Days of Being Wild', 'Eros', 'Fallen Angels', 'Happy Together', 'In the Mood for Love', 'The Grandmaster']

updatedDict = \
{'2046': ['Tony Chiu-Wai Leung',
          'Carina Lau',
          'Chang Chen',
          'Maggie Cheung',
          'Siu Ping-Lam',
          'To-Hoi Kong'],
 'As Tears Go By': ['Maggie Cheung', 'Jacky Cheung', 'To-Hoi Kong'],
 'Ashes of Time': ['Leslie Cheung',
                   'Maggie Cheung',
                   'Tony Chiu-Wai Leung',
                   'Jacky Cheung',
                   'Carina Lau',
                   'Charlie Yeung'],
 'Chungking Express': ['Tony Chiu-Wai Leung'],
 'Days of Being Wild': ['Leslie Cheung',
                        'Maggie Cheung',
                        'Carina Lau',
                        'Jacky Cheung',
                        'Tony Chiu-Wai Leung'],
 'Eros': ['Chang Chen'],
 'Fallen Angels': ['Charlie Yeung', 'To-Hoi Kong'],
 'Happy Together': ['Leslie Cheung', 'Tony Chiu-Wai Leung', 'Chang Chen'],
 'In the Mood for Love': ['Maggie Cheung',
                          'Tony Chiu-Wai Leung',
                          'Siu Ping-Lam'],
 'The Grandmaster': ['Tony Chiu-Wai Leung',
                     'Chang Chen',
                     'To-Hoi Kong',
                     'Siu Ping-Lam',
                     'Charlie Yeung']}

# {'2046': <Movie id:0212712[http] title:_2046 (2004)_>,
#  'As Tears Go By': <Movie id:0096461[http] title:_As Tears Go By (1988)_>,
#  'Ashes of Time': <Movie id:0109688[http] title:_Ashes of Time (1994)_>,
#  'Chungking Express': <Movie id:0109424[http] title:_Chungking Express (1994)_>,
#  'Days of Being Wild': <Movie id:0101258[http] title:_Days of Being Wild (1990)_>,
#  'Eros': <Movie id:0343663[http] title:_Eros (2004)_>,
#  'Fallen Angels': <Movie id:0112913[http] title:_Fallen Angels (1995)_>,
#  'Happy Together': <Movie id:0118845[http] title:_Happy Together (1997)_>,
#  'In the Mood for Love': <Movie id:0118694[http] title:_In the Mood for Love (2000)_>,
#  'The Grandmaster': <Movie id:1462900[http] title:_The Grandmaster (2013)_>}